version: "3"

services:
  python3:
    build: .
    container_name: "python3"
    ports:
      - 8081:8081
    volumes:
      - .:/python
    # 選項是告訴 Docker 要分配一個虛擬終端機（pseudo-tty）並綁定到 container 的標準輸入上
    tty: true
    